# Generated by Django 2.1.3 on 2018-12-03 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('YelpData', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('photo_id', models.AutoField(primary_key=True, serialize=False)),
                ('caption', models.CharField(max_length=1024)),
                ('label', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'photo',
                'verbose_name_plural': 'photos',
                'db_table': 'photo',
                'managed': False,
            },
        ),
    ]
